name: Deploy Frontend to S3

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET }}
  CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
  VITE_API_BASE: ${{ vars.VITE_API_BASE }}
  VITE_SHOPIFY_API_KEY: ${{ vars.VITE_SHOPIFY_API_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: frontend autoupdate variables
    defaults:
      run:
        working-directory: frontend
    permissions:
      id-token: write   # for OIDC
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build
        env:
          VITE_API_BASE: ${{ env.VITE_API_BASE }}
          VITE_SHOPIFY_API_KEY: ${{ env.VITE_SHOPIFY_API_KEY }}

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # Long-cache all hashed assets (Vite puts them in dist/assets)
      - name: Upload assets with far-future cache
        run: |
          aws s3 sync dist s3://$S3_BUCKET \
            --delete \
            --exclude "index.html" \
            --cache-control "public, max-age=31536000, immutable"

      # Upload index.html with no-store so clients always fetch latest
      - name: Upload index.html with no-store
        run: |
          aws s3 cp dist/index.html s3://$S3_BUCKET/index.html \
            --cache-control "no-store" \
            --content-type "text/html; charset=utf-8"

      - name: Invalidate CloudFront (index + manifest + route shell)
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/index.html" "/assets/*" "/"
